name = "cloudflare-playwright-example"
main = "src/index.ts"
workers_dev = true
compatibility_flags = ["nodejs_compat", "enable_nodejs_fs_module"]
compatibility_date = "2025-09-01"
upload_source_maps = true

[browser]
binding = "MYBROWSER"

[observability]
enabled = true
