name = "cloudflare-playwright-example"
main = "src/index.ts"
workers_dev = true
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-05"
upload_source_maps = true

unsafe.bindings = [
   {name = "MYBROWSER", type = "browser", internal_env = "https://core-staging.rendering.cfdata.org/"},
]
