name: "Playwright for Cloudflare - Pre-Release"
permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  test_smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Generate Pre-Release
        run: |
          npm ci
          cd packages/playwright-cloudflare
          npm run build
          npx pkg-pr-new publish
