name: "publish Cloudflare release - NPM"

on:
  push:
    branches: 
      - publish-action

jobs:
  cf-release:
    name: "publish to NPM"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: cd packages/playwright-cloudflare
      - run: npm run build
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
